server:
    port: 8000

power:
    interval: 1000

oxygen:
    reductionUriMap:
        normal: http://o2normal.xploregroup.net/oxygen
        premium: http://o2premium.xploregroup.net/oxygen
    type: normal

logging:
    file: joe.log
